### PR TITLE
Support multiple bot responses/performance enhancements/bug fixes/deployment feature

### PR DESCRIPTION
**Pull request by daltskin**
I've made a few changes to allow the following:

- Support multiple responses coming back from the bot (current implementation only responds to the first response in reply) with configurable timeout delay.
- Added Deploy to Azure - make it super easy to deploy this solution (for evaluation and testing) with default parameters and allow botId/directline secret to be entered during provisioning stage
- Added Progressive Response - Will return a "working on it message" whilst data is still be retrieved from the bot to give progress feedback to end user
- Now uses websockets - improve performance of the bridge
- Fixed app insights bug and added more logging
- Added ability to change the directline endpoint

I've tested deploying this in different data centers including West Europe/North Europe and West US.  Regardless of the directline endpoint, West US is the most performant by far (hence added to Readme.md).

### CODE REVIEW

**Comment by cmnisal** [comment]
Nice :D

**Comment by tobecodex** [comment]
LGTM - Let's talk when you're next available

**Comment by daltskin** [comment]
Use xhr2 instead of xmlhttprequest to resolve an issue I'm seeing in North Europe data center to address the below:

Application has thrown an uncaught exception and is terminated:

Unexpected token E in JSON at position 0
    at Object.parse (native)
    at parseXhrResponse (D:\home\site\wwwroot\node_modules\rxjs\observable\dom\AjaxObservable.js:402:29)
    at new AjaxError (D:\home\site\wwwroot\node_modules\rxjs\observable\dom\AjaxObservable.js:387:25)
    at xhrReadyStateChange [as onreadystatechange] (D:\home\site\wwwroot\node_modules\rxjs\observable\dom\AjaxObservable.js:332:38)
    at dispatchEvent (D:\home\site\wwwroot\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (D:\home\site\wwwroot\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at handleError (D:\home\site\wwwroot\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (D:\home\site\wwwroot\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:459:14)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at ClientRequest.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)

**Comment by tobecodex** [comment]
lgtm

**Pull request merged**
